### ISSUE TITLE
incompatible character encodings: Windows-1251 and ASCII-8BIT

### ISSUE THREAD

**Issue by newmen** [whitequark/cyberplat_pki#4]
Cyberplat works with windows-1251 encoding, but when I try to sign a string in cp1251, I get error:

```
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/cyberplat_pki-2.0.5/lib/cyberplat_pki/key.rb:84:in `sign': incompatible character encodings: Windows-1251 and ASCII-8BIT (Encoding::CompatibilityError)
```

**Comment by whitequark** [comment]
Try `.force_encoding('ASCII-8BIT')` before signing.

**Comment by whitequark** [comment]
Fixed by #5.

**Comment by newmen** [comment]
The authorization server returns an error when I do force_encoding before signing and then send the request Technical support said that the error occurs due incorrect signing the message. Trying to do force_encoding after signing also came to nothing lead.
At the moment the problem was solved by using a Russian::translit before signing.

**Comment by grindars** [comment]
You don't need to do any force_encoding's, gem will keep input encoding by itself.

Are you sure that you're using master revision of gem? I have checked gem output just now, and it's byte-by-byte identical with native library.
